INSERT INTO kdo VALUES ('Hugo', 'Arc');
INSERT INTO kdo VALUES ('Yannis', 'Canne a peche');
INSERT INTO kdo VALUES ('Yassine', 'Pomme doree');
INSERT INTO kdo VALUES ('Chemsdine', 'Torche');
INSERT INTO kdo VALUES ('Abderrahim', 'Torche de redstone');
INSERT INTO kdo VALUES ('Nour-Eddine', 'Montre');
INSERT INTO kdo VALUES ('Khosgerel', 'Boussole');
INSERT INTO kdo VALUES ('Lilian', 'Pancarte');
INSERT INTO kdo VALUES ('Kadir', 'Cisailles');
INSERT INTO kdo VALUES ('Emile', 'Seau');
INSERT INTO kdo VALUES ('Solal', 'Entonnoir');
INSERT INTO kdo VALUES ('Yanis', 'Bouclier');
INSERT INTO kdo VALUES ('Fabio', 'Pelle');
INSERT INTO kdo VALUES ('Baptiste', 'Pioche');
INSERT INTO kdo VALUES ('Timothee', 'Houe');
INSERT INTO kdo VALUES ('Berdan', 'Hache');
INSERT INTO kdo VALUES ('Yunus-Emre', 'Epee');
INSERT INTO kdo VALUES ('Kelyan', 'Armure');
INSERT INTO kdo VALUES ('Karen', 'Wagonnet');
INSERT INTO kdo VALUES ('Theo', 'Etabli');
INSERT INTO kdo VALUES ('Yann', 'Baton');
INSERT INTO kdo VALUES ('Aquila', 'Bloc musical');
INSERT INTO kdo VALUES ('Louis', 'Crochet');
INSERT INTO kdo VALUES ('Umut', 'Fiole');
INSERT INTO kdo VALUES ('Hasbi', 'Oeil de l Ender');
INSERT INTO kdo VALUES ('Andreas', 'Creme de magma');
INSERT INTO kdo VALUES ('Yasin', 'Boule de feu');
INSERT INTO kdo VALUES ('Elma', 'Pot de fleur');
INSERT INTO kdo VALUES ('Romain', 'Fourneau');